### ISSUE TITLE
Feature request: Expose the gas_used value directly

### ISSUE THREAD

**Issue by tocklime** [pavoni/pyloopenergy#29]
In my home assistant, I'm using the loop energy sensor to monitor my gas and electric. I use the integration sensor to recover 'total energy used ever', and then the utility_meter sensor to get 'kWh used today'. The integration sensor works great for the constantly varying electricity, but is quite inaccurate over  the slowly updating gas. 

It looks like pyloopenergy actually receives the total used (current gas meter reading?) and then calculates a current rate from that. 

I think it would be useful to also expose the gas meter reading so that I don't need to do the kWh -> kW -> kWh conversions I'm doing at the moment (and having true gas meter reading in home assistant would be super useful when I submit my meter readings to the energy company).

What do you think?

I see you're not very active on this project. I'd be interested in putting a pull request together if you think it would be useful.

**Comment by tocklime** [comment]
Nevermind, I see what I want is already exposed at this level. I'll go see about the home assistant loop sensor.

**Comment by pavoni** [comment]
Sounds good - PR very welcome if you need to modify anything.

Shout if you need any help.
