### ISSUE TITLE
No handlers could be found for logger "socketio_client"

### ISSUE THREAD

**Issue by azimhusain** [pavoni/pyloopenergy#30]
Hi there @pavoni 

My update script appears to have just stopped working out of the blue yesterday afternoon. Reboot usually solves, but that didn't work. The virtual machine running this has no other services, so there's no conflict. 

When trying to execute getloopvalue.py manually I see

> [root@pvout pvout]# python getloopvalue.py 
> /usr/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.22) or chardet (2.2.1) doesn't match a supported version!
>   RequestsDependencyWarning)
> No handlers could be found for logger "socketIO_client"

And then the process just hangs. 

Done a yum update on the OS
Updated pip + did a pip update of pyloopenergy

Still no luck. 

Any idea what the problem could be? Happy to provide any logging files if that helps!

Thank you!

**Comment by owainlloyd** [comment]
Same issue and time as above. Last reading was received at  was 15:44 on the 7th March.

**Comment by azimhusain** [comment]
> Same issue and time as above. Last reading was received at was 15:44 on the 7th March.

My last log was 15:40, too! Glad it's not just me... 
Could be a certificate issue? Has loop changed their system somehow?

**Comment by pavoni** [comment]
Same here. My simple debug demo traces the following.
```
❯ python demo.py                                                                                                                                                                                                                                         ⏎
INFO:root:Started
INFO:pyloopenergy.loop_energy:Started LoopEnergy thread
INFO:pyloopenergy.loop_energy:Opening socket connection
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.your-loop.com:443
DEBUG:urllib3.connectionpool:https://www.your-loop.com:443 "GET /socket.io/1/ HTTP/1.1" 400 None
WARNING:socketIO_client:[waiting for connection] unexpected status code (400)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.your-loop.com:443
DEBUG:urllib3.connectionpool:https://www.your-loop.com:443 "GET /socket.io/1/ HTTP/1.1" 400 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.your-loop.com:443
DEBUG:urllib3.connectionpool:https://www.your-loop.com:443 "GET /socket.io/1/ HTTP/1.1" 400 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.your-loop.com:443
```

So guess they changed something (this stuff is all undocumented).

**Comment by pavoni** [comment]
OK looks like loop updated their very old socket.IO server to 2.0, the library was using the very old 0.9 version. Looks to work OK on my system.

So if you switch to library version `0.1.0` it should work.
