### ISSUE TITLE
Simple subscription example - Not returning anything

### ISSUE THREAD

**Issue by Jbithell** [pavoni/pyloopenergy#5]
```
import pyloopenergy
import time

def elec_trace():
    print("Electricity =", le.electricity_useage)

elec_serial = '000000000000' #Not my actual serial!
elec_secret = 'secret'

le = pyloopenergy.LoopEnergy(elec_serial, elec_secret)
le.subscribe_elecricity(elec_trace)
time.sleep(120)
le.terminate()
time.sleep(60)
```

Calling this script outputs nothing - even after waiting a couple of minutes!

**Comment by Jbithell** [comment]
Having played about quite a bit, and at one point getting it to return something, its back to its old ways of not returning anything

**Comment by Jbithell** [comment]
It may be because of the message I am getting on the "My Devices" page saying readings are `Not arriving`

**Comment by pavoni** [comment]
@Jbithell Sorry missed this for some reason.

If you're not getting updates on the webpage - then this won't work.

I don't know if it will produce any extra data if you turn logging on but might help. You can do by adding

`logging.basicConfig(level=logging.DEBUG)` to the top of the loop of `pyloopenergy/loop_energy.py`

There is quite a bit of helpful tracing from the socket.io library - and a little from my code.

But sounds like the loop energy server isn't connecting to your local hub if you're not seeing MyDevices on their web page.

**Comment by Jbithell** [comment]
Yes, I spoke to the team at Loop and they agreed that there was an issue with my receiver, moving it around fixed the issue!

**Comment by pavoni** [comment]
Perfect - glad you got it working!
