### ISSUE TITLE
Conversion value

### ISSUE THREAD

**Issue by spants** [pavoni/pyloopenergy#8]
How do I work out the conversion value, any tips?. My reading is 2.83 x higher on Loop dashboard than the value... Do I just fudge it or is there a more scientific way? :-)

**Comment by pavoni** [comment]
The base calculation is

`M3 x Calorific value 39.4 x volume correction 1.02264 / 3.6 = 11.1922`

So my guess is your meter isn't reading cubic meters. If you can find out what it reads we can add an alternative calculation.

If you take a look at https://github.com/pavoni/pyloopenergy/blob/master/pyloopenergy/loop_energy.py#L146 you can see what comes back from my meter.

Perhaps compare with yours and see if we can find which is used to specify the meter type. We can use that to pick the calculation.

**Comment by pavoni** [comment]
This looks helpful.
http://utilitiessavings.co.uk/resources/gas-conversion-tool-convert-meter-readings-into-kwh/

**Comment by pavoni** [comment]
If can get the meter reading like the ones I linked - I can add your meter.

**Comment by pavoni** [comment]
@spants I asked Loop Energy support who were very helpful - esp given all this is unsupported!

The status bytes don't contain the meter type - so I'll just add it as a config option when you initialise the device.

Will let you know when I've updated the code.

**Comment by spants** [comment]
Thanks - been away so I havent had any more opportunity to play. But I did build loop2mqtt.py which works perfectly using your library!

**Comment by pavoni** [comment]
@spants Can you check if this new version works for you. You can now specify a meter type.

````
pyloopenergy.LoopEnergy(elec_serial, elec_secret, gas_serial, gas_secret, pyloopenergy.IMPERIAL)

````

**Comment by spants** [comment]
Not sure what is wrong but I get an error: 

Exception in thread LoopEnergy Event Thread:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/boot/config/plugins/loop2mqtt/pyloopenergy/loop_energy.py", line 125, in _run_event_thread
    Namespace) as socket_io:
  File "/usr/lib64/python2.7/site-packages/socketIO_client/__init__.py", line 206, in __init__
    self.define(Namespace)
  File "/usr/lib64/python2.7/site-packages/socketIO_client/__init__.py", line 223, in define
    namespace = Namespace(self._transport, path)
  File "/usr/lib64/python2.7/site-packages/socketIO_client/__init__.py", line 333, in _transport
    socketIO_session, self._transport_name)
  File "/usr/lib64/python2.7/site-packages/socketIO_client/__init__.py", line 381, in _get_transport
    }[transport_name](session, self.is_secure, self._base_url, **self._kw)
  File "/usr/lib64/python2.7/site-packages/socketIO_client/transports.py", line 147, in __init__
    self._connection = websocket.create_connection(url, header=headers)
  File "/usr/lib64/python2.7/site-packages/websocket/_core.py", line 487, in create_connection
    skip_utf8_validation=skip_utf8_validation, **options)
TypeError: __init__() got an unexpected keyword argument 'header'

**Comment by spants** [comment]
The new library works fine - thanks!. Is there a way to do a manual read on a cron for these values rather than the socket.io method? I'm logging data for home automation and my script dies after 4 days or so.

**Comment by pavoni** [comment]
Glad it works.

Mine does run ok for long periods (now the reconnect logic is working).

I think you could write a command line utility to output the values on the callback (or set some state to wait for both) and then terminate cleanly, and then call this from a cron. The loop energy callbacks for initial state include two gas readings - so you get an initial state quickly.

None of the loop energy api is documented or supported yet - so hard to know if there is a simple request api!
